### ISSUE TITLE
error when run inpaint func

### ISSUE THREAD

**Issue by ZHANG-SHI-CHANG** [rin-23/RobustSkinWeightsTransferCode#2]
Very excellent project!!
When I used my own assets, I encountered a libigl error "Error: Numerical issue" in the inpaint function. How to solve it?
Below is the data from my experiment
[skinweight_test_data.zip](https://github.com/rin-23/RobustSkinWeightsTransferCode/files/15304042/skinweight_test_data.zip)

**Comment by rin-23** [comment]
Hello, I will test it today/tmr and come back to you. Just need to check the topology sometimes small disconneted mesh pieces might cause numerical issues. But I will check, thank you for reporting!

**Comment by HJYblur** [comment]
Hi, thanks for the great work! However, I encountered the same problem using my own data. Is there any update regarding this problem?

**Comment by rin-23** [comment]
@HJYblur sry for the delay, doing this right now, if you have a test data you want me to check pls attach a zip file.

**Comment by rin-23** [comment]
@ZHANG-SHI-CHANG  ok I figured out the problem. Your target mesh had 2 unreferenced vertices which then caused the laplacian to not be computed correctly. I will update the code to handle this edge case right now. Please try and let me know if it works for you.

@HJYblur maybe this was a problem for you too?

**Comment by rin-23** [comment]
@ZHANG-SHI-CHANG should be resolved now with commit e2e30b9

**Comment by HJYblur** [comment]
> @HJYblur sry for the delay, doing this right now, if you have a test data you want me to check pls attach a zip file.

Hi, sorry for the late reply, we deleted some of the ornaments on the surface to get the mesh clean before it could run smoothly, according to your guessing. Thanks for the help:)

**Comment by rinatepic** [comment]
Cool. For now the code mainly handles nice manifold meshes. You can technically make it more robust (and we do that in  C++ UE implementation) by first finding all connected components of a target mesh and doing a transfer for each component individually.
There could be cases where the component will not find any matches on the source, in which case you can use a simple closest point method as a fallback just for that component.

**Comment by rin-23** [comment]
Cool. For now the code mainly handles nice manifold meshes. You can technically make it more robust (and we do that in C++ UE implementation) by first finding all connected components of a target mesh and doing a transfer for each component individually.
There could be cases where the component will not find any matches on the source, in which case you can use a simple closest point method as a fallback just for that component.

**Comment by ZHANG-SHI-CHANG** [comment]
> @ZHANG-SHI-CHANG should be resolved now with commit [e2e30b9](https://github.com/rin-23/RobustSkinWeightsTransferCode/commit/e2e30b9a047fb6d09dcd81094e084cf744da7b8d)

Thank you very much for your reply! I have solved the problem by myself, by removing discrete points and adding post-processing to give them weights; and I also encountered the effect problem when migrating clothes with multiple disconnected components. Currently, I migrate them one by one in a certain order. I wonder if there is a better solution? Thanks again for your reply

**Comment by rin-23** [comment]
the thing with multiple components is when a component cant find any matches at all on the source then it cant really do any inpainting. In that case you can either just fall back to the closest point method or maybe try to use a robust laplacian like this Blender plugin built on top of my work- https://github.com/sentfromspacevr/robust-weight-transfer

its only like 1 line change really - https://github.com/sentfromspacevr/robust-weight-transfer/blob/5ea046eea358c4898e1a15c5bd4a33222d015e6d/weighttransfer.py#L132
